version: "3"

services:
  port_scraper:
    container_name: "port_scraper"
    build: .
    depends_on:
      - mariadb
    volumes:
      - ./config/:/port_scraper/config
  mariadb:
    container_name: "mariadb"
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./dbmaria:/config/databases/
    environment:
      - MARIADB_ROOT_PASSWORD=root
  grafana:
    container_name: "grafana"
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=
      - GF_USERS_DEFAULT_THEME=light
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning