apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    url: mariadb:3306
    database: port_scraper
    user: root
    jsonData:
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+
    secureJsonData:
      password: root