{
 "title": "Port Scraper",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Total scanned IPs",
   "type": "stat",
   "description": "Total number of DISTINCT scanned IPs",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT(IP)) FROM scan"
    }
   ]
  },
  {
   "title": "Total scanned Titles",
   "type": "stat",
   "description": "Number of DISTINCT scanned Titles (different of empty)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT(HTTPtitle)) FROM scan WHERE HTTPtitle != \"\""
    }
   ]
  },
  {
   "title": "Total scanned Ports ",
   "type": "stat",
   "description": "Number of DISTINCT scanned Titles (different of empty)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT(Port)) FROM scan"
    }
   ]
  },
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(Port) as CountPort, Latitude, Longitude FROM scan GROUP BY Latitude, Longitude"
    }
   ]
  },
  {
   "title": "scan table",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "port_scraper",
     "rawSql": "SELECT\n\tId,\n\tINET_NTOA(IP),\n\tscan.Port,\n\tport.Service as PortService,\n\tOpen,\n\tLatency,\n\tHTTPstatus,\n\tHTTPtitle,\n\tHTTPserver,\n\tHTTPfavicon,\n\tfavicon.Service as HTTPfaviconService,\n\tServiceInfo,\n\tTLS,\n\tTLScertificate,\n\tCountryCode,\n\tDistrict,\n\tCity,\n\tLatitude,\n\tLongitude,\n\tTimestamp\nFROM port_scraper.scan \nLEFT JOIN port_scraper.favicon ON scan.HTTPfavicon  = favicon.Hash \nLEFT JOIN port_scraper.port ON scan.Port  = port.Port \nWHERE $__timeFilter(Timestamp)"
    }
   ]
  }
 ]
}